# 2 dimensional list is needed
import numpy as np

def writecoords(coordlist, projectname = 'simu_pkg'):

    natom = np.shape(coordlist)[0]

    if np.shape(coordlist)[1] == 3:

        print('COORD| ***warning*** 3 column-atomic coordinates list detected! Please make sure that it'
             +'      is what you want. A raw will be printed out for check:')
        print(coordlist[0])
        ifquit = input('COORD| ***warning*** you can decide now if quit program. (y/n)')

        if ifquit == 'y':

            exit()
            print('COORD| ***error*** program quit from CoordWrite subroutine.')

        else:

            print('COORD| ***warning*** program will proceed continuely. Coordinates will be treated as'
                 +'      single-element, element symbol you need to input...')
            element = input('COORD| ***warning*** waiting for an element symbol input, all elements are supported.')

            if element:

                coordoutput = []
                for i in range(natom):

                    line = coordlist[i][:]
                    line.insert(0, element)
                    coordoutput.append(line)
    
    elif np.shape(coordlist)[1] == 4:

        coordoutput = coordlist

    else:

        print('COORD| ***error*** bad input format. program stoppted at CoordWrite routine. quit.')
        exit()

    print('COORD| write coordinates to file. name after '+str(projectname)+' , standard xyz file(s) output.')

    filename = projectname+'-pos-out.xyz'
    filetag = open(filename, 'a+', encoding='utf-8')

    filetag.writelines(str(natom)+'\n')
    filetag.writelines('Generated by simu_pkg coordWrite routine.\n')
    for iline in range(natom):

        filetag.writelines(
            "%3.3s"%coordoutput[iline][0]+' '
            +"%20.10f"%coordoutput[iline][1]
            +"%20.10f"%coordoutput[iline][2]
            +"%20.10f"%coordoutput[iline][3]
            +'\n'
            )
    
    filetag.close()
